In [5]:


# 2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

# 3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
# arrays.





# 5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?














import numpy as np

In [6]:
# 1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. 
# How does it enhance Python's capabilities for numerical operations?

# A key Python library for data analysis and scientific computing is called NumPy 
# (Numerical Python). It offers strong tools for managing sizable, 
# multi-dimensional arrays and matrices in addition to a number of mathematical 
# operations that can be performed effectively on these arrays.
# Here's how NumPy improves upon Python's features and why data analysis 
# and scientific computing benefit from using it.


#Numpy (numerical Python) - enhances python's capabilities by providing efficient, 
#high-performance tools for handling and manipulating large datasets,performing complex
#mathematical operations, and integrating with other scientific libraries. its ability
#to streamline numerical operations and improve performance



In [7]:
# 2. Compare and contrast np.mean() and np.average() functions in NumPy. 
#When would you use one over the other?

#both np.mean() and np.average() are functions in numpy used to calculate the average of an
#array. 

#np.mean() - is ideal for calculating a simple average with equal weighting for all elements
#np.average() - is perferred when you need to calculate a weighted average.

#np.mean() - as it do not  involve weight is slighlty faster and less computationally 
#intensive 
#np.average() - it is slower than np.mean() and has additional steps 

element = [1,2,3,4]
np.mean(element)

2.5

In [8]:
np.average(element)

2.5

In [9]:
# 3. Describe the methods for reversing a NumPy array along different axes. 
#Provide examples for 1D and 2D arrays.

#reversing a numpy array can be done efficiently using slicing and specific numpy function.


In [10]:
#reversing a 1D array
#syntax : array[::-1]
arr = np.array([1,2,3,4,5])
reversed = arr[::-1]
reversed

array([5, 4, 3, 2, 1])

In [11]:
#reversing a 2D array
#syntax reversed columns: array[::-1,:]
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
reversed = arr_2d[:,::-1]
reversed

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [12]:
#reversed_rows
#syntax : [::-1,:]
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
reversed = arr_2d[::-1,:]
reversed

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [13]:
#reversed both
# syntax : [::-1,::-1]
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
reversed = arr_2d[::-1,::-1]
reversed

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [14]:
# 4. How can you determine the data type of elements in a NumPy array? 
#Discuss the importance of data types in memory management and performance.

In [15]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [16]:
arr.dtype

dtype('int32')

In [17]:
fl = np.array([1.2,2.3,3.4])
fl

array([1.2, 2.3, 3.4])

In [18]:
fl.dtype

dtype('float64')

In [19]:
complex = np.array([2+3j,3+4j, 4+5j])
complex

array([2.+3.j, 3.+4.j, 4.+5.j])

In [20]:
complex.dtype

dtype('complex128')

In [21]:
# The data type (dtype) of a NumPy array is critical for memory management and computational performance.
# Choosing an appropriate data type allows you to balance memory usage and speed, making your applications more efficient.
# You can determine the data type of elements in an array using the dtype attribute, which provides insight into how the array is stored and processed in memory.

In [22]:
# 5. Define ndarrays in NumPy and explain their key features. 
#How do they differ from standard Python lists?

#ndarray(N-dimensional array) is the core data structure that provides a powerful way to 
#store and manipulate large amounts of numerical data. An 'ndarray' is a multidimensional,
#homogenous array of fixed-size items, where each element in the array is of the same data
#type

#Key features of ndarray
# 1. Homogenous data : all elements in an 'ndarray' are of the same type, defined by the 
#"dtype" attribute. this uniformity allows for efficient storage and operation, as the 
#underlying memory representation is consistent.

# 2. Multidimensional: An ndarray can have any number of dimensions, specified by its shape 
#(a tuple of integers). The dimensions correspond to the rank of the array, and NumPy supports 
# arrays of arbitrary dimensions (1D, 2D, 3D, etc.).

#3. Fixed Size: Once created, the size of an ndarray is fixed. While you can reshape or 
# create new arrays, the number of elements in an array cannot change without creating a new
#array.


In [23]:
# Memory Efficiency: The data type of an array directly influences the amount of memory 
# required to store the array
# Choosing the Right Data Type: By selecting an appropriate data type, you can optimize 
# memory usage.
# Choosing the Right Data Type: By selecting an appropriate data type, you can optimize 
# memory usage.
# Computation Speed: Operations on arrays with smaller data types generally execute 
# faster because they involve fewer bits.
# CPU Cache Efficiency: Smaller data types mean that more data can fit into the CPU 
# cache, potentially reducing the need for memory access and speeding up computation.

In [24]:
# 6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

#Numpy arrays provides a specific speed advantage ovr python list. this is because numpy is built in C, which is the fastest coding language.
# The syntax used in mathematical operationsa are easy to use, concise and readable.
# Numpy itself has collection of functions and operations which help us to reduce manual coding.
# it uses less memory as compare to list because it uses homogenous data type which helps usimg efficient memory utilization compare to list.
# Numpy has built-in functions for performing complex mathematical operations which are not only faster but more reliable than writing your own functions from the scratch.
# Python list cannot work in multidimensional data operations where as array is has multidimensional array support.


In [25]:
list = [1,2,3,4,5,6,7,8]
for i in list:
    print(i,end=" ") #HERE, you can see we are using extra effot and time for list

1 2 3 4 5 6 7 8 

In [26]:
np.arange(1,9)# but using numpy its way easier

array([1, 2, 3, 4, 5, 6, 7, 8])

In [49]:
# 7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
# output.

#V-stack - 
# V (vertically) stack means stack arrays in vertical sequence or row wise.
# this is like concatenation of a matrix with a 1-D array 

#Syntax :
#np.vstack(tup,dtype=None, casting='same_kind')

a = np.random.randint(1,10,size = (3,4))
a

b = np.random.randint(11,20, size = (1,4))
b

np.vstack((a, b))

#in the resultant we can see we have concatenated matrix A with array B
#this is an example of vstack


array([[ 4,  2,  8,  5],
       [ 6,  4,  7,  8],
       [ 9,  1,  5,  9],
       [19, 17, 19, 11]])

In [56]:
#H-stack - 
# H (horizontally) stack means stack arrays in horizontal sequence or row wise.
# this is like concatenation of a matrix with a 1-D array 

#Syntax :
#np.hstack(tup,dtype=None, casting='same_kind')
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
a
b = np.array([21,22,23,24])
b

array([21, 22, 23, 24])

In [60]:
bb = b.reshape(4,1)
bb

array([[21],
       [22],
       [23],
       [24]])

In [64]:
np.hstack((a,bb)) # here we can see we have concatenated a matrix with an array.

array([[ 1,  2,  3, 21],
       [ 4,  5,  6, 22],
       [ 7,  8,  9, 23],
       [10, 11, 12, 24]])

In [83]:
# 8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
# array dimensions.

#this is a normal array created for the difference
arr = np.random.randint(1,100, size = (4,5))
arr
 # in 2-Dimension 


array([[35, 28, 73, 44, 99],
       [97, 28, 21, 67, 54],
       [81, 86, 57, 55, 66],
       [43, 89, 39, 33, 79]])

In [84]:
#fliplr :
# it flips the array horizontally (axis = 1)
#
#example :
horizontal_flip = np.fliplr(arr)
horizontal_flip

array([[99, 44, 73, 28, 35],
       [54, 67, 21, 28, 97],
       [66, 55, 57, 86, 81],
       [79, 33, 39, 89, 43]])

In [85]:
#flipud :
#it flips the array vertically(axis = 0)
#example :
vertical_flip = np.flipud(arr)
vertical_flip 

array([[43, 89, 39, 33, 79],
       [81, 86, 57, 55, 66],
       [97, 28, 21, 67, 54],
       [35, 28, 73, 44, 99]])

In [88]:
# 3 Dimensional 
ap = np.random.randint(2,20,size =(3,4,5))
ap

array([[[15, 18,  5,  9, 14],
        [17, 17, 13, 11,  2],
        [11, 19, 12,  3, 15],
        [18, 19, 19, 17, 10]],

       [[11, 15,  3,  5, 11],
        [16, 14, 11,  9,  3],
        [ 3, 19, 15, 18,  3],
        [14, 19, 18,  4,  7]],

       [[ 5, 13,  8, 13,  7],
        [18,  7,  2, 11, 16],
        [ 9, 10, 11, 18,  3],
        [17, 18, 18,  4, 18]]])

In [90]:
#3D horizontal flip
horizontal = np.fliplr(ap)
horizontal
#in horizontal the elements flipped within it axis

array([[[18, 19, 19, 17, 10],
        [11, 19, 12,  3, 15],
        [17, 17, 13, 11,  2],
        [15, 18,  5,  9, 14]],

       [[14, 19, 18,  4,  7],
        [ 3, 19, 15, 18,  3],
        [16, 14, 11,  9,  3],
        [11, 15,  3,  5, 11]],

       [[17, 18, 18,  4, 18],
        [ 9, 10, 11, 18,  3],
        [18,  7,  2, 11, 16],
        [ 5, 13,  8, 13,  7]]])

In [91]:
#3D veritcal flip
vertical = np.flipud(ap)
vertical
# in vertical flip >>> the elements has flipped it axis 

array([[[ 5, 13,  8, 13,  7],
        [18,  7,  2, 11, 16],
        [ 9, 10, 11, 18,  3],
        [17, 18, 18,  4, 18]],

       [[11, 15,  3,  5, 11],
        [16, 14, 11,  9,  3],
        [ 3, 19, 15, 18,  3],
        [14, 19, 18,  4,  7]],

       [[15, 18,  5,  9, 14],
        [17, 17, 13, 11,  2],
        [11, 19, 12,  3, 15],
        [18, 19, 19, 17, 10]]])

In [98]:
# 9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

#array_split() method in numpy is used to split an array into multiplt sub arrays.
#the difference between array_split() and split() is unlike split(), array_split() can divide into specific indices.


arr = np.array([1,2,3,4,5,6,7,8])
arr
split = np.array_split(arr,[2,4,6])
split
#here you can see we have split an array into specific splits.



[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]

In [102]:
# 10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute 
#to efficient array operations?

#Both Vectorization and Broadcasting are important in numpy. they are performed on arrays. lets underswtand them one by one

#Vectorization :
#it is a technique to perform operations on arrays without using loops. it uses inbuilt 
#precompiled functions and operations like "+,-,*,/" etc to perform on arrays 

#it is used to increase the speed  of the python program.

#Syntax :
#np.vectorize()

# it can be done within a single array.
arr12 = np.array


In [108]:
#Broadcasting :
#by broadcastingwe perform arithmetic operations on arrays of different shapes.

# unlike the usual way of performing arithematic operations on same shape of arays element by
#element, by broadcasting we can do arithmetic operations on different shapes

#Snytax :
# np.broadcast()

#it can be done between arrays of different dimensions.

arr3D = np.random.randint(2,20, size = (2,3,4))

arr2D = np.array([[1],[2],[3]])

result = arr3D * arr2D
result

array([[[ 8, 17, 19,  9],
        [ 8, 26, 32, 14],
        [21,  9, 15, 21]],

       [[17, 11,  6,  4],
        [14, 10, 18, 14],
        [51, 51,  9, 12]]])