In [73]:
import numpy as np

In [74]:
# 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then,
# interchange its rows and columns.

arr = np.random.randint(1,101,(3,3))
arr

array([[ 7, 35, 81],
       [97,  3, 59],
       [66, 80, 90]])

In [75]:
transpose_arr = arr.T
transpose_arr

array([[ 7, 97, 66],
       [35,  3, 80],
       [81, 59, 90]])

In [76]:
# 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array,
# then into a 5x2 array.


In [77]:
arr_1d = np.array([1,2,3,4,5,6,7,8,9,10])
arr_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
arr_1d.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [79]:
arr_1d.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [80]:
# 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, 
# resulting in a 6x6 array.


In [81]:
array1 = np.random.rand(4,4)
array1

array([[0.97539326, 0.60500597, 0.85923591, 0.26631183],
       [0.47550673, 0.93705978, 0.37772048, 0.82723669],
       [0.98814668, 0.07926626, 0.90939344, 0.9690793 ],
       [0.99771572, 0.48876771, 0.9581071 , 0.80634895]])

In [82]:
np.pad(array1,pad_width =1)

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.97539326, 0.60500597, 0.85923591, 0.26631183,
        0.        ],
       [0.        , 0.47550673, 0.93705978, 0.37772048, 0.82723669,
        0.        ],
       [0.        , 0.98814668, 0.07926626, 0.90939344, 0.9690793 ,
        0.        ],
       [0.        , 0.99771572, 0.48876771, 0.9581071 , 0.80634895,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

In [83]:
# 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

arr = np.arange(10,61,5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

In [84]:

# 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case 
# transformations (uppercase, lowercase, title case, etc.) to each element.


In [85]:
a = np.array(['python','numpy','pandas'])
a

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [86]:
np.char.upper(a)

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [87]:
np.char.lower(a)

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [88]:
np.char.capitalize(a)

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

In [89]:
np.char.islower(a)

array([ True,  True,  True])

In [90]:
np.char.swapcase(a)

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [91]:
b = np.array(['asd      s','d   sd','     zxc','   aer    ','retew      '])
b

array(['asd      s', 'd   sd', '     zxc', '   aer    ', 'retew      '],
      dtype='<U11')

In [92]:
np.char.strip(b)

array(['asd      s', 'd   sd', 'zxc', 'aer', 'retew'], dtype='<U11')

In [93]:
np.char.split(a)

array([list(['python']), list(['numpy']), list(['pandas'])], dtype=object)

In [94]:
np.char.strip(b)

array(['asd      s', 'd   sd', 'zxc', 'aer', 'retew'], dtype='<U11')

In [95]:
np.char.title(b)

array(['Asd      S', 'D   Sd', '     Zxc', '   Aer    ', 'Retew      '],
      dtype='<U11')

In [96]:
# 6. Generate a NumPy array of words. Insert a space between each character of every word in 
# the array.
arr = np.array(['Py','thon','Pan','Das'])
arr



array(['Py', 'thon', 'Pan', 'Das'], dtype='<U4')

In [97]:
np.char.join(' ',arr)

array(['P y', 't h o n', 'P a n', 'D a s'], dtype='<U7')

In [98]:
# 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, 
    #multiplication, and division.
pr = np.random.randint(1,10,(3,4))
pr

array([[9, 3, 8, 9],
       [8, 2, 6, 9],
       [7, 7, 1, 1]])

In [99]:
rr = np.random.randint(11,20,(3,4))
rr

array([[18, 19, 15, 19],
       [11, 19, 12, 11],
       [11, 12, 14, 15]])

In [100]:
#addition
pr + rr

array([[27, 22, 23, 28],
       [19, 21, 18, 20],
       [18, 19, 15, 16]])

In [101]:
#subtraction
rr - pr

array([[ 9, 16,  7, 10],
       [ 3, 17,  6,  2],
       [ 4,  5, 13, 14]])

In [102]:
#multiply
rr * pr

array([[162,  57, 120, 171],
       [ 88,  38,  72,  99],
       [ 77,  84,  14,  15]])

In [103]:
#devide
rr/pr

array([[ 2.        ,  6.33333333,  1.875     ,  2.11111111],
       [ 1.375     ,  9.5       ,  2.        ,  1.22222222],
       [ 1.57142857,  1.71428571, 14.        , 15.        ]])

In [104]:
# 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.
iden_matrix = np.eye(5)
iden_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [105]:
diagonal = np.diagonal(iden_matrix)

In [106]:
diagonal

array([1., 1., 1., 1., 1.])

In [120]:
# 9. Generate a NumPy array of 100 random integers between 0 and 1000. 
# Find and display all prime numbers in this array.
arr123 = np.random.randint(0,1001,size = 100)
arr123

array([409, 968, 986, 152, 301, 343, 652, 887, 966, 429, 840, 410, 625,
       200, 738, 969, 963, 861,  22, 812, 399, 360, 410, 819,  75, 535,
       789, 657, 233,  81, 630, 352, 185,  58, 942, 986, 885, 859, 192,
       189, 896, 500, 405, 646,  86, 460, 350, 100, 574, 383, 766, 241,
        88, 201, 130, 833, 832, 263, 882, 219, 892, 135, 963, 624, 425,
       965, 303, 789, 158, 738, 865, 362, 125, 228, 817,   6, 818, 854,
       524, 854, 112, 835, 355,  50, 975, 421, 866, 739, 122, 856,  16,
       649, 870, 881, 178, 336, 941,  13, 365, 224])

In [123]:
def prime(n):
    if n <= 1:
        return False
    for i in range(2,1001):
        if n % i == 0:
            return False
    return True

prime_no = [ x for x in arr123 if prime(x)]
print(prime_no)

[]


In [108]:
# 10. Create a NumPy array representing daily temperatures for a month.
# Calculate and display the weekly averages.

In [124]:
daily_temp = np.random.uniform(0,40, size = 28)
daily_temp

array([19.34752023,  4.43421232, 34.37198811, 18.02485271, 38.55880793,
       15.53962741,  1.58366361, 35.13581956,  9.98244385, 24.09984703,
       34.62425995, 10.45389582, 27.47060604, 30.09387347,  1.49744974,
       18.90256842, 28.05307216, 38.69276123, 19.85312359,  1.20836519,
       11.4124163 ,  7.94349434, 20.24497343,  1.57445396,  6.61618684,
        7.80790503,  6.96313575, 27.93299071])

In [125]:
week= daily_temp.reshape(4,7)
week

array([[19.34752023,  4.43421232, 34.37198811, 18.02485271, 38.55880793,
        15.53962741,  1.58366361],
       [35.13581956,  9.98244385, 24.09984703, 34.62425995, 10.45389582,
        27.47060604, 30.09387347],
       [ 1.49744974, 18.90256842, 28.05307216, 38.69276123, 19.85312359,
         1.20836519, 11.4124163 ],
       [ 7.94349434, 20.24497343,  1.57445396,  6.61618684,  7.80790503,
         6.96313575, 27.93299071]])

In [129]:
weekly_average = np.mean(week,axis = 1)
weekly_average

array([18.8372389 , 24.5515351 , 17.08853666, 11.29759144])